export const LOADING = "LOADING";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CLEAR_FORM_ERRORS = 'CLEAR_FORM_ERRORS';

export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const EMAIL_VALIDATION_FAILED = 'EMAIL_VALIDATION_FAILED';
export const PASSWORD_VALIDATION_FAILED = 'PASSWORD_VALIDATION_FAILED';

export const LOG_OUT = 'LOG_OUT';